general:
  root_path: ../safety_benchmarks/benchmarks/radimagenet  # Root path of the csv file.
  csv_name: instances.csv # Name of the csv file (ONLY one column listed paths to vnnlibs).
model:
  name: radimagenet_model
  path: ../safety_benchmarks/benchmarks/radimagenet/pytorch/resnet50_torch.pt  # Path to PyTorch checkpoint.
  input_shape: [1, 3, 224, 224] # The vnnlib does not have input shape information, user should specify here.
data:
  dataset: MITBIH
  start: 0
  end: 100
solver:
  batch_size: 512 # Number of subdomains to compute in parallel in bound solver. Decrease if you run out of memory.
bab:
  timeout: 120  # Timeout threshold for branch and bound. Increase for verifying more points.
attack:
  pgd_order: skip